from __future__ import annotations

import os
import sys
from pathlib import Path


# Location of files bundled with the program.
RESOURCE_DIR = Path(__file__).resolve().parent


def get_user_data_directory() -> Path:
    """
    Return the folder used for files generated by the application.
    """

    # Packaged PyInstaller application
    if getattr(sys, "frozen", False):
        local_app_data = os.getenv("LOCALAPPDATA")

        if local_app_data:
            return (
                Path(local_app_data)
                / "H2_Raman_Temperature_Fitter"
            )

        return (
            Path.home()
            / "H2_Raman_Temperature_Fitter"
        )

    # Normal Python development version
    return RESOURCE_DIR


DATA_DIR = get_user_data_directory()

LIBRARY_DIR = DATA_DIR / "generated_libraries"
SPECTRA_DIR = DATA_DIR / "generated_spectra"

LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
SPECTRA_DIR.mkdir(parents=True, exist_ok=True)